# Generated by Django 4.1.2 on 2024-06-14 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
    ]
