# Generated by Django 4.1.2 on 2024-05-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graficas',
            fields=[
                ('cod_Grafica', models.AutoField(db_column='codigoGrafica', primary_key=True, serialize=False)),
                ('nombreGrafica', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('precioDolar', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='graficas')),
            ],
        ),
        migrations.CreateModel(
            name='Monitores',
            fields=[
                ('cod_Monitor', models.AutoField(db_column='codigoMonitor', primary_key=True, serialize=False)),
                ('nombreMonitor', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('precioDolar', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='monitores')),
            ],
        ),
        migrations.CreateModel(
            name='Mouses',
            fields=[
                ('cod_Mouse', models.AutoField(db_column='codigoMouse', primary_key=True, serialize=False)),
                ('nombreMouse', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('precioDolar', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='mouses')),
            ],
        ),
        migrations.CreateModel(
            name='Procesadores',
            fields=[
                ('cod_Procesador', models.AutoField(db_column='codigoProcesador', primary_key=True, serialize=False)),
                ('nombreProcesador', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('precioDolar', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='procesadores')),
            ],
        ),
        migrations.CreateModel(
            name='Teclados',
            fields=[
                ('cod_Teclado', models.AutoField(db_column='codigoTeclado', primary_key=True, serialize=False)),
                ('nombreTeclado', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('precioDolar', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='teclados')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
