# Generated by Django 4.1.2 on 2024-06-21 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0003_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='usuario',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='asunto',
            field=models.CharField(choices=[('consulta', 'Consulta'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('otro', 'Otro')], max_length=20),
        ),
    ]
