# Generated by Django 4.1.2 on 2024-05-30 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_categoria_marca_productos_delete_graficas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='precioDolar',
        ),
        migrations.AddField(
            model_name='productos',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.marca'),
        ),
    ]
