# Generated by Django 4.1.2 on 2024-05-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_remove_productos_preciodolar_productos_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='SrcImagen',
            field=models.CharField(default='Imagen', max_length=300),
        ),
    ]
