# Generated by Django 4.1.2 on 2024-06-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_solicitud_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
