# Generated by Django 4.1.2 on 2024-05-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_productos_srcimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precioDolar',
            field=models.FloatField(default=0.0),
        ),
    ]
