# Generated by Django 4.1.2 on 2024-06-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_productos_preciodolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='SrcImagen',
            field=models.CharField(default='./Images/Productos/', max_length=300),
        ),
    ]
