# Generated by Django 4.1.2 on 2024-06-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_productos_srcimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
